### ISSUE TITLE
Feature request: support for Custom Resource Definitions

### ISSUE THREAD

**Issue by moltar** [tommy351/kubernetes-models-ts#1]
It would be great to get support for Custom Resource Definitions. Or at least a tutorial on how to generate these.

A great first one would be KubeDB: https://kubedb.com

If you can document how to do this, I can work on it.

We can either pile them up in this repo, or create separate repos for each CRD group.

Thanks!

**Comment by tommy351** [comment]
I have no idea how to export OpenAPI definitions of CRD from Kubernetes so far. I tried `/openapi/v2` and `/swagger.json` but only built-in resources are provided. Will try `kubectl get crd` later.

Links: 
- https://kubernetes.io/docs/concepts/overview/kubernetes-api/#openapi-and-swagger-definitions
- https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation

**Comment by moltar** [comment]
What about this kind of spec format:

https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/cert-manager.yaml

Can this be converted to OpenAPI format?

**Comment by tommy351** [comment]
I wrote a package [@kubernetes-models/crd-generate](https://github.com/tommy351/kubernetes-models-ts/blob/master/packages/crd-generate) to generate Kubernetes models from CRD files. The packages below are generated with it.

- [@kubernetes-models/cert-manager](https://github.com/tommy351/kubernetes-models-ts/blob/master/packages/cert-manager)
- [@kubernetes-models/contour](https://github.com/tommy351/kubernetes-models-ts/blob/master/packages/contour)

**Comment by moltar** [comment]
Oh nice one!! Thanks 😀
