### ISSUE TITLE
Discussion: better type support

### ISSUE THREAD

**Issue by moltar** [tommy351/kubernetes-models-ts#2]
It would be great to get better type support for `oneOf` and these kind of attributes via enums. 

Right now all such attributes are strings.

E.g. for `imagePullPolicy`, the interface should be something like:

```ts
{
   imagePullPolicy: ImagePullPolicy.IF_NOT_PRESENT // enum
}
```

I realize it'd be a pretty major breaking change though. Also, the migrations would be more difficult, or not even possible. But I figured at least I can start the discussion going.

**Comment by tommy351** [comment]
It would be difficult because the code is generated from Kubernetes OpenAPI schema currently, which doesn't contain any information about enums.

**Comment by moltar** [comment]
Right, I didn't realize they don't have the `oneOf` option on these. So odd.
