### ISSUE TITLE
error: BigInt is not defined in node v8.10.0

### ISSUE THREAD

**Issue by AshinWu** [tommy351/kubernetes-models-ts#36]
error: BigInt is not defined in node_modules/@kuberneter-model/validate/dist/ajv.js:20:17
But I don't want to upgrade node version. How can I resolve it?

**Comment by tommy351** [comment]
Node.js 8 support has been dropped since 
[v1.0.0](https://github.com/tommy351/kubernetes-models-ts/blob/master/packages/kubernetes-models/CHANGELOG.md#100-2020-10-13). You have to downgrade if you want to use kubernetes-models on Node.js 8.

**Comment by AshinWu** [comment]
> Node.js 8 support has been dropped since
> [v1.0.0](https://github.com/tommy351/kubernetes-models-ts/blob/master/packages/kubernetes-models/CHANGELOG.md#100-2020-10-13). You have to downgrade if you want to use kubernetes-models on Node.js 8.

how can i downgrade?
The dependencies "@kubernetes-models/validate": "^1.1.0" is use "^", it looks as if the downgrade was ineffective 
```
dependencies: {
   "kubernetes-models": "1.0.0"
}
```
it not work for me.

**Comment by AshinWu** [comment]
I rewirte dependencies in my package.json, it work for me.
```
{
  "@kubernetes-models/base": "1.2.0",
  "@kubernetes-models/validate“: "1.1.0",
  "kubernetes-models": "1.1.0"
}
```
