### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by juanrgm** [tommy351/kubernetes-models-ts#40]
Hi! Firstly, thanks you for your job.

I am having problems with `loadChart` (ex: `nginx-ingress` or `mariadb`). 

The json schema does not support `null` values and this is a problem for some manifests (https://github.com/nginxinc/kubernetes-ingress/blob/fba8fb6387820e9a5ac8848b2b6335a939725ee7/deployments/helm-chart/templates/controller-configmap.yaml#L12). 

```ts
// components/test.ts
import { loadString } from "@kosko/yaml";

const configMap = loadString(`
apiVersion: v1
kind: ConfigMap
metadata:
  name: test
data:
`);

configMap.then(console.log)

export default [configMap];
```

```sh
npx kosko generate
```
```
[
  IoK8sApiCoreV1ConfigMap {
    apiVersion: 'v1',      
    kind: 'ConfigMap',
    metadata: { name: 'test' },
    data: null
  }
]
ValidationError: data.data should be object
- path: "D://repo//@juanrgm//cluster//components//test.ts"
- index: [0, 0]
- kind: "v1/ConfigMap"
- name: "test"
```

**Comment by tommy351** [comment]
I think the workaround you mentioned might be the solution. I will try to implement it in kubernetes-models. At the same time, you can
