### ISSUE TITLE
Additional properties for contour CRD

### ISSUE THREAD

**Issue by bgrande12** [tommy351/kubernetes-models-ts#74]
**Describe the bug**
`cookieRewritePolicies` property is missing from the contour model -- https://projectcontour.io/docs/v1.21.0/config/cookie-rewriting/. It's possible there are other properties but this is the one I've found. I was able to run crd-generate but not sure where the generated model is suppose to go

**To Reproduce**
1. Try to create an HTTPProxy object with `cookieRewritePolicies` 

**Expected behavior**
To be able to define a `cookieRewritePolicies`

**Additional context**

**Comment by tommy351** [comment]
CRD versions has been updated to v1.21.0 in `@kubernetes-models/contour@3.1.0`.
