### ISSUE TITLE
ArgoCD CRD source seems to be broken

### ISSUE THREAD

**Issue by dayflower** [tommy351/kubernetes-models-ts#85]
**Describe the bug**
Cannot import `ApplicationSet` from `@kubernetes-models/argo-cd/argoproj.io/v1alpha1`.

**To Reproduce**
1. `npm install @kubernetes-models/argo-cd`
2. try to import `ApplicationSet` from `@kubernetes-models/argo-cd`
3. Definition is missing.

**Expected behavior**
Should be able to import `@kubernetes-models/argo-cd`

**Additional context**
Source URL is broken?

https://github.com/tommy351/kubernetes-models-ts/blob/9f2521d86920e2a886749ec6b0736e4a8343f04f/third-party/argo-cd/package.json#L48

Correct URL would be: https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.0/manifests/crds/applicationset-crd.yaml

**Comment by tommy351** [comment]
Fixed in `@kubernetes-models/argo-cd@2.0.2`.
